version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - simple-crud-project
    restart: always
  db:
    container_name: db_
    hostname: db
    build:
      context: ./db
      dockerfile: ./Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    networks:
      - simple-crud-project
    restart: always
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - ./server/.env
      - .env
    ports:
      - 3001:3001
    networks:
      - simple-crud-project
    restart: always

networks:
  simple-crud-project:
